# fly.toml app configuration file generated for rb185-todos on 2023-07-12T09:24:55-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rb185-todos"
primary_region = "bog"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
